version: '3.4'

services:
  squoosh:
    container_name: squoosh
    image: squoosh
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5001:5001
